redmine-5.0-private/plugins/redmine_contacts/config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

#custom routes for this plugin
  resources :contacts, :path_names => {:contacts_notes => 'notes'} do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :contacts_notes
      post :bulk_edit, :bulk_update, :send_mails, :preview_email
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'contacts#show', :as => "tabs"
      get 'load_tab' => 'contacts#load_tab', :as => "load_tab"
    end
    resources :contacts_projects, :path => "projects", :only => [:new, :create, :destroy]
  end

  resources :projects do
    resources :contacts, :path_names => {:contacts_notes => 'notes'} do
      collection do
        get :contacts_notes
      end
    end
    resources :contact_imports, :only => [:new, :create, :show] do
      member do
        get :settings
        post :settings
        get :mapping
        post :mapping
        get :run
        post :run
      end
    end
    resources :deal_imports, :only => [:new, :create, :show] do
      member do
        get :settings
        post :settings
        get :mapping
        post :mapping
        get :run
        post :run
      end
    end
    resources :deal_categories

  end
  resources :deals do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email
      post :bulk_edit, :bulk_update, :send_mails, :update_form
      put :update_form
      delete :bulk_destroy
    end
    member do
      put :add_product, defaults: { format: :json }
    end
  end

  resources :projects do
    resources :deals, :only => [:new, :create, :index]
    resources :deal_categories, :only => [:new, :create, :index]
  end

  resources :deal_categories, :only => [:edit, :update, :destroy]

  resources :deal_statuses, :except => :show do
    collection do
      put :assign_to_project
    end
  end

  resources :projects do
    resources :crm_queries, :only => [:new, :create]
  end

  resources :crm_queries, :except => [:show]

  resources :notes

  match '/contacts_tags', :controller => 'contacts_tags', :action => 'destroy', :via => :delete

  resources :contacts_tags do
    collection do
      post :merge, :context_menucha
      get :context_menu, :merge
    end
  end

  match 'contacts/:contact_id/duplicates' => 'contacts_duplicates#index', :via => [:get, :post]

  match 'projects/:project_id/deal_categories/new' => 'deal_categories#new', :via => [:get, :post]


  match 'auto_completes/taggable_tags' => 'auto_completes#taggable_tags', :via => :get, :as => 'auto_complete_taggable_tags'
  match 'auto_completes/contact_tags' => 'auto_completes#contact_tags', :via => :get, :as => 'auto_complete_contact_tags'
  match 'auto_completes/contacts' => 'auto_completes#contacts', :via => :get, :as => 'auto_complete_contacts'
  match 'auto_completes/companies' => 'auto_completes#companies', :via => :get, :as => 'auto_complete_companies'
  match 'auto_completes/deals' => 'auto_completes#deals', :via => :get, :as => 'auto_complete_deals'

  match 'users/new_from_contact/:id' => 'users#new_from_contact', :via => :get
  match 'contacts_duplicates/:action' => 'contacts_duplicates', :via => [:get, :post]
  match 'contacts_duplicates/search' => 'contacts_duplicates#search', :via => :get, :as => 'contacts_duplicates_search'
  match 'contacts_issues/:action' => 'contacts_issues', :via => [:get, :post, :delete, :put]
  match 'contacts_vcf/:action' => 'contacts_vcf', :via => [:get, :post]
  match 'deal_contacts/:action' => 'deal_contacts', :via => [:get, :post, :delete]
  match 'deals_tasks/:action' => 'deals_tasks', :via => [:get, :post, :put]
  match 'contacts_settings/:action' => 'contacts_settings', :via => [:get, :post]
  match 'contacts_mail_handler/:action' => 'contacts_mail_handler', :via => [:get, :post]
  match 'attachments/contacts_thumbnail/:id(/:size)', :controller => 'attachments', :action => 'contacts_thumbnail', :id => /\d+/, :via => :get

redmine-5.0-private/plugins/redmine_contacts/app/helpers/contacts_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

module ContactsHelper

  def contact_tabs(contact)
    contact_tabs = []
    contact_tabs << {:name => 'notes', :partial => 'contacts/notes', :label => l(:label_crm_note_plural)} if contact.visible?
    contact_tabs << {:name => 'contacts', :partial => 'company_contacts', :label => l(:label_contact_plural) + (contact.company_contacts.visible.count > 0 ? " (#{contact.company_contacts.count})" : "")} if contact.is_company?
    contact_tabs << {:name => 'deals', :partial => 'deals/related_deals', :label => l(:label_deal_plural) + (contact.all_visible_deals.size > 0 ? " (#{contact.all_visible_deals.size})" : "") } if User.current.allowed_to?(:add_deals, @project)
    contact_tabs
  end

  def settings_contacts_tabs
    ret = [
      {:name => 'general', :partial => 'settings/contacts/contacts_general', :label => :label_general},
      {:name => 'tags', :partial => 'settings/contacts/contacts_tags', :label => :label_crm_tags_plural},
      {:name => 'deal_statuses', :partial => 'settings/contacts/contacts_deal_statuses', :label => :label_crm_deal_status_plural},
    ]
    ret.push({:name => 'hidden', :partial => 'settings/contacts/contacts_hidden', :label => :label_crm_contacts_hidden}) if params[:hidden]
    ret
  end

  def collection_for_visibility_select
    [[l(:label_crm_contacts_visibility_project), Contact::VISIBILITY_PROJECT],
     [l(:label_crm_contacts_visibility_public), Contact::VISIBILITY_PUBLIC],
     [l(:label_crm_contacts_visibility_private), Contact::VISIBILITY_PRIVATE]]
  end

  def contact_list_styles_for_select
    list_styles = [[l(:label_crm_list_excerpt), "list_excerpt"]]
    list_styles += [[l(:label_crm_list_list), "list"],
                    [l(:label_crm_list_cards), "list_cards"]]
  end

  def contacts_list_style
    list_styles = contact_list_styles_for_select.map(&:last)
    if params[:contacts_list_style].blank?
      list_style = list_styles.include?(session[:contacts_list_style]) ? session[:contacts_list_style] : RedmineContacts.default_list_style
    else
      list_style = list_styles.include?(params[:contacts_list_style]) ? params[:contacts_list_style] : RedmineContacts.default_list_style
    end
    session[:contacts_list_style] = list_style
  end

  def authorized_for_permission?(permission, project, global = false)
    User.current.allowed_to?(permission, project, :global => global)
  end

  def render_contact_projects_hierarchy(projects)
    s = ''
    project_tree(projects) do |project, level|
      s << "<ul>"
      name_prefix = (level > 0 ? ('&nbsp;' * 2 * level + '&#187; ') : '')
      s << "<li id='project_#{project.id}'>" + name_prefix + link_to_project(project)

      s += ' ' + link_to(image_tag('delete.png'),
                                 contact_contacts_project_path(@contact, :id => project.id, :project_id => @project.id),
                                 :remote => true,
                                 :method => :delete,
                                 :style => "vertical-align: middle",
                                 :class => "delete",
                                 :title => l(:button_delete)) if (projects.size > 1 && User.current.allowed_to?(:edit_contacts, project))
      s << "</li>"

      s << "</ul>"
    end
    s.html_safe
  end

  def contact_to_vcard(contact)
    return false unless ContactsSetting.vcard?

    card = Vcard::Vcard::Maker.make2 do |maker|

      maker.add_name do |name|
        name.prefix = ''
        name.given = contact.first_name.to_s
        name.family = contact.last_name.to_s
        name.additional = contact.middle_name.to_s
      end

      maker.add_addr do |addr|
        addr.preferred = true
        addr.street = contact.street1.to_s.gsub("\r\n"," ").gsub("\n"," ")
        addr.locality = contact.city.to_s
        addr.region = contact.region.to_s
        addr.postalcode = contact.postcode.to_s
        addr.country = contact.country.to_s
        addr.location = 'business'
      end

      maker.title = contact.job_title.to_s
      maker.org = contact.company.to_s
      maker.birthday = contact.birthday.to_date unless contact.birthday.blank?
      maker.add_note(contact.background.to_s.gsub("\r\n"," ").gsub("\n", ' '))

      maker.add_url(contact.website.to_s)

      contact.phones.each { |phone| maker.add_tel(phone) }
      contact.emails.each { |email| maker.add_email(email) }
    end
    avatar = contact.attachments.find_by_description('avatar')
    card = card.encode.sub("END:VCARD", "PHOTO;BASE64:" + "\n " + [File.open(avatar.diskfile).read].pack('m').to_s.gsub(/[ \n]/, '').scan(/.{1,76}/).join("\n ") + "\nEND:VCARD") if avatar && avatar.readable?

    card.to_s

  end
  def contacts_to_vcard(contacts)
    return "" unless User.current.allowed_to?(:export_contacts, @project, :global => true)
    contacts.map{|c| contact_to_vcard(c) }.join("\r\n")
  end

  def contacts_to_xls(contacts)
    return "" unless User.current.allowed_to?(:export_contacts, @project, :global => true)
    require 'spreadsheet'

    Spreadsheet.client_encoding = 'UTF-8'
    book = Spreadsheet::Workbook.new
    sheet = book.create_worksheet
    headers = [ "#",
            l(:field_is_company),
            l(:field_contact_first_name),
            l(:field_contact_middle_name),
            l(:field_contact_last_name),
            l(:field_contact_job_title),
            l(:field_contact_company),
            l(:field_contact_phone),
            l(:field_contact_email),
            l(:label_crm_address),
            l(:label_crm_city),
            l(:label_crm_postcode),
            l(:label_crm_region),
            l(:label_crm_country),
            l(:field_contact_skype),
            l(:field_contact_website),
            l(:field_birthday),
            l(:field_contact_tag_names),
            l(:label_crm_assigned_to),
            l(:field_contact_background),
            l(:field_created_on),
            l(:field_updated_on)
            ]
    order_condition = 'LOWER(name)'
    order_condition += ' COLLATE "C"' if ActiveRecord::VERSION::MAJOR < 6 && ActiveRecord::Base.connection.adapter_name.downcase =~ /postgresql/
    custom_fields = ContactCustomField.order(order_condition)
    custom_fields.each { |f| headers << f.name }
    idx = 0
    row = sheet.row(idx)
    row.replace headers

    contacts.each do |contact|
      idx += 1
      row = sheet.row(idx)
      fields = [contact.id,
                  contact.is_company ? 1 : 0,
                  contact.first_name,
                  contact.middle_name,
                  contact.last_name,
                  contact.job_title,
                  contact.company,
                  contact.phone,
                  contact.email,
                  contact.address.to_s.gsub("\r\n"," ").gsub("\n", ' '),
                  contact.city,
                  contact.postcode,
                  contact.region,
                  contact.country,
                  contact.skype_name,
                  contact.website,
                  format_date(contact.birthday),
                  contact.tag_list.to_s,
                  contact.assigned_to ? contact.assigned_to.name : "",
                  contact.background.to_s.gsub("\r\n"," ").gsub("\n", ' '),
                  format_date(contact.created_on),
                  format_date(contact.updated_on)
                  ]
      contact.custom_field_values.sort_by{|v| v.custom_field.name.downcase}.each {|custom_value| fields << RedmineContacts::Utils::CsvUtils.csv_custom_value(custom_value) }
      row.replace fields
    end

    xls_stream = StringIO.new('')
    book.write(xls_stream)

    return xls_stream.string
  end

  def mail_macro(contact, message)
    message = message.gsub(/%%NAME%%/, contact.first_name)
    message = message.gsub(/%%FULL_NAME%%/, contact.name)
    message = message.gsub(/%%COMPANY%%/, contact.company) if contact.company
    message = message.gsub(/%%LAST_NAME%%/, contact.last_name) if contact.last_name
    message = message.gsub(/%%MIDDLE_NAME%%/, contact.middle_name) if contact.middle_name
    message = message.gsub(/%%DATE%%/, format_date(Date.today.to_s))

    contact.custom_field_values.each do |value|
      message = message.gsub(/%%#{value.custom_field.name}%%/, value.value.to_s)
    end
    message
  end

  def set_flash_from_bulk_contact_save(contacts, unsaved_contact_ids)
    if unsaved_contact_ids.empty?
      flash[:notice] = l(:notice_successful_update) unless contacts.empty?
    else
      flash[:error] = l(:notice_failed_to_save_contacts,
                        :count => unsaved_contact_ids.size,
                        :total => contacts.size,
                        :ids => '#' + unsaved_contact_ids.join(', #'))
    end
  end

  def render_contact_tabs(tabs)
    if tabs.any?
      render :partial => 'common/contact_tabs', :locals => {:tabs => tabs}
    else
      content_tag 'p', l(:label_no_data), :class => "nodata"
    end
  end

  def importer_link
    project_contact_imports_path
  end

  def importer_show_link(importer, project)
    project_contact_import_path(:id => importer, :project_id => project)
  end

  def importer_settings_link(importer, project)

redmine-5.0-private/plugins/redmine_contacts/app/views/contacts/_attributes.html.erb
<div id="attributes" class="attributes">
<div class="contextual">
	 <%- if ContactsSetting.vcard? -%>
    <%= link_to 'vCard', contact_path(@contact, :format => :vcf) %>
  <%- end -%>
</div>
<h3><%= if !@contact.is_company then l(:label_contact) else l(:label_crm_company) end %></h3>

<table class="contact sidebar attributes vcard">
  <%= call_hook(:view_contacts_sidebar_attributes_top) %>
	<tr>
		<th class = "name"><%= l(:field_contact_name) %>:</th><td class="name fn <%= "org" if @contact.is_company %>"><%= h @contact.name(:firstname_middlename_lastname) %></td>
	</tr>
	<% if !@contact.job_title.blank? %>
	<tr> <th class = "job_title"><%= !@contact.is_company ? l(:field_contact_job_title) : l(:field_company_field) %>:</th><td class="job_title title"><%= h @contact.job_title %></td></tr>
	<% end %>
	<% if !@contact.is_company %>
	<tr><th class = "company"><%=l(:field_contact_company)%>:</th><td class="company org"><%= h @contact.company %></td></tr>
	<% end %>
	<tr>
		<th class = "address"><%= l(:field_contact_address) %>:</th>
		<% unless @contact.address.blank? %>
		<td class="address adr">
				<%= @contact.post_address.gsub("\n", "<br/>").html_safe %>
				<br>
				<%= link_to l(:label_crm_show_on_map), "http://maps.google.com/maps?f=q&q=#{@contact.address}+(#{@contact.name})&ie=UTF8&om=1"%>
		</td>
		<% end %>
		</tr>
	<tr class = "tel">
		<th class = "phone"><%= l(:field_contact_phone) %>:</th>
		<td class = "phones">
		<% @contact.phones.each do |phone| %>
			<span  class="value"><%= h phone %> <br></span>
		 <% end %>
		</td>
	</tr>
	<tr class = "emails">
		<th><%= l(:field_contact_email) %>:</th>
		<td>
			<% @contact.emails.each do |email| %>
				<span class="email"><%= mail_to email %> <br></span>
			 <% end %>
		</td>
	</tr>
	<tr>
		<th class = "website"><%= l(:field_contact_website) %>:</th>
		<td class="website url"><%= link_to @contact.website, @contact.website_address, :class => 'external' %></td>
	</tr>
	<% if !@contact.skype_name.blank? %>
	<tr>
	  <th class = "skype"><%= l(:field_contact_skype) %>:</th>
	  <td class="skype"><%= skype_to @contact.skype_name %></td>
	</tr>
	<% end %>
	<% if !@contact.birthday.blank? %>
	<tr> <th class = "birthday"><%= l(:field_birthday) %>:</th><td class="birthday bday" title=<%= "#{format_date(@contact.birthday)}" %>><%= "#{@contact.birthday.day} #{t('date.month_names')[@contact.birthday.month]}"%></td> </tr>
	<tr> <th class = "age"><%= l(:field_age) %>:</th><td class="ega"><%= @contact.age %></td> </tr>
	<% end %>
	<% @contact.custom_field_values.compact.each do |custom_value| %>
		<% if !custom_value.value.blank? %>
		<tr> <th class = "custom_field"><%= custom_value.custom_field.name%>:</th><td> <%= simple_format_without_paragraph(h(show_value(custom_value))) %></td> </tr>
		<% end %>
	<% end %>

  <% if @contact.assigned_to %>
  <tr><th class="author"><%=l(:label_crm_assigned_to)%>:</th><td class="author"><%= avatar(@contact.assigned_to, :size => "14") %><%= link_to_user(@contact.assigned_to)  %></td></tr>
  <% end %>

	<%= call_hook(:view_contacts_sidebar_attributes_bottom) %>

</table>

</div>

redmine-5.0-private/plugins/redmine_contacts/app/views/contacts/_contact_card.html.erb
<div class="contact card">
	<table class="subject_header">
		<tr>
			<td class="avatar"><%= contact_tag(contact_card, :type => "avatar", :size => 64) %></td>
			<td class="name" style="vertical-align: top;">
				<h2><%= contact_tag(contact_card, :type => "plain") %> </h2>
				<p>
				<%= h contact_card.job_title %>
				<% if !contact_card.is_company %>
				<%= " #{l(:label_crm_at_company)} " unless (contact_card.job_title.blank? or contact_card.company.blank?) %>
  				<% if contact_card.contact_company %>
  					<%= link_to contact_card.contact_company.name, {:controller => 'contacts', :action => 'show', :project_id => contact_card.contact_company.project(@project), :id => contact_card.contact_company.id } %>
  				<% else %>
  					<%= h contact_card.company %>
  				<% end %>
				<% end %>
			  </p>

			</td>


		</tr>
		<tr>
			<td colspan="2" style="padding-left: 10px;">
	  		<% if contact_card.phones.any? %>
				  <p class="phone icon icon-phone"><%=  contact_card.phones.first %></p>
				<% end %>

				<% if contact_card.emails.any? %>
				  <p class="email icon icon-email"><%= mail_to contact_card.emails.first %></p>
				<% end %>
				<%= tag_links(contact_card.tag_list) %>
			</td>
		</tr>
	</table>
</div>

redmine-5.0-private/plugins/redmine_contacts/app/views/contacts/_form.html.erb
<%= back_url_hidden_field_tag %>
<%= error_messages_for 'contact' %>
<div class = "box tabular" id="contact_data">

<script type="text/javascript" charset="utf-8">
  function togglePerson(element) {
  if (element.checked) {
    $('#person_data').hide();
    $('#job_title label').get(0).innerHTML ='<%= l(:field_company_field) %>';
    $('#first_name label').get(0).innerHTML='<%= l(:field_company_name) %>' + '<span class="required"> *</span>';

  } else {
    $('#person_data').show();
     $('#job_title label').get(0).innerHTML ='<%= l(:field_contact_job_title) %>';
    $('#first_name label').get(0).innerHTML='<%= l(:field_contact_first_name) %>' + '<span class="required"> *</span>';
  }

  }
</script>

  <p class="avatar extended" id="watchers">
  <%= avatar_to(@contact, :size => "64", :style => "vertical-align: middle;") %>
  <%= link_to image_tag('delete.png'), {:controller => 'attachments', :action => 'destroy', :id => @contact.avatar},
                                        :data => {:confirm => l(:text_are_you_sure)},
                                        :method => :delete,
                                        :class => 'delete',
                                        :style => "vertical-align: middle;",
                                        :title => l(:button_delete) unless @contact.avatar.blank? %>
  </p>
  <p class="extended">
  <%= label_tag l(:field_contact_avatar) %>
  <span id="attachments_fields"></span>
  <span class="add_attachment">
  <%= file_field_tag 'dummy_file',
        :size => 30,
        :id => nil,
        :class => 'file_selector',
        :multiple => true,
        :onchange => 'uploadAvatar(this);',
        :data => {
          :max_file_size => Setting.attachment_max_size.to_i.kilobytes,
          :max_file_size_message => l(:error_attachment_too_big, :max_size => number_to_human_size(Setting.attachment_max_size.to_i.kilobytes)),
          :max_concurrent_uploads => Redmine::Configuration['max_concurrent_ajax_uploads'].to_i,
          :upload_path => uploads_path(:format => 'js'),
          :description_placeholder => l(:label_optional_description)
        } %>
  </span>
  </p>
  <p><%= f.check_box(:is_company, :label => l(:field_contact_is_company), :onclick => "togglePerson(this)" ) %></p>
  <p id="first_name"><%= f.text_field :first_name, :label => !@contact.is_company ? l(:field_contact_first_name) : l(:field_company_name), :required => true, :style => "width:90%;" %></p>
  <div id="person_data" style="<%= 'display: none;' if @contact.is_company  %>">

  <p><%= f.text_field :middle_name, :label=>l(:field_contact_middle_name) %></p>
  <p><%= f.text_field :last_name, :label=>l(:field_contact_last_name), :id => 'contact_last_name' %></p>
  <p><%= f.text_field :company, :label=>l(:field_contact_company) -%></p>
  <%= javascript_tag "observeAutocompleteField('contact_company', '#{escape_javascript auto_complete_companies_path}')" %>
  <p class="extended"><%= f.text_field :birthday, :size => 12, :type =>'date' %><%= calendar_for('contact_birthday') %> </p>
  </div>
  <p id="job_title"><%= f.text_field :job_title, :label => !@contact.is_company ? l(:field_contact_job_title) : l(:field_company_field) %></p>
  <% @contact.build_address if @contact.address.blank? %>
  <%= f.fields_for(:address) do |a| %>
  <span class="extended">
  <%= render :partial => 'common/address_form', :locals => {:f => a} %>
  </span>

  <% end %>

  <div id="phones_fields">
  <p>
  <%= f.text_field :phone, :label=>l(:field_contact_phone), :style => "width:90%;" -%>
  <br>
  <em class="info"><%= l(:text_comma_separated) %></em>
   </p>
  </div>

  <p>
  <%= f.text_field 'email', :label=>l(:field_contact_email), :style => "width:90%;" -%>
  <br>
  <em class="info"><%= l(:text_comma_separated) %></em>
  </p>

  <p class="extended"><%= f.text_field 'website', :label=>l(:field_contact_website) -%></p>
  <p class="extended"><%= f.text_field 'skype_name', :label=>l(:field_contact_skype) -%></p>
  <% @contact.custom_field_values.each do |value| %>
    <p class="<%= "extended" unless value.custom_field.is_required? %>">
      <%= custom_field_tag_with_label :contact, value %>
    </p>
  <% end -%>
  <p class="extended notes"><%= f.text_area :background , :cols => 80, :rows => 8, :class => 'wiki-edit', :label=>l(:field_contact_background)  %></p>
  <%= wikitoolbar_for 'contact_background' %>

  <p class="extended">
  <%= label_tag l(:label_crm_tags_plural) %>
  <%= render :partial => "contacts_tags/tags_form" %>
  </p>

  <% if @project %>
  <p class="extended"><%= f.select :assigned_to_id, (@project.assignable_users.collect {|m| [m.name, m.id]}), :include_blank => true, :label => l(:label_crm_assigned_to) %></p>
  <% end %>

  <p class="extended"><%= f.select :visibility, collection_for_visibility_select, :include_blank => false, :label => l(:label_crm_contacts_visibility) %></p>

  <p id="show_details_link" style="display: none;"><%= link_to l(:label_crm_show_details), "javascript:void(0);", :onclick => "$('#contact_data .extended').show();" %></p>

</div>

redmine-5.0-private/plugins/redmine_contacts/app/views/contacts/_list_excerpt.html.erb
<%= form_tag({}, :data => {:cm_url => context_menu_contacts_path}) do %>
<%= hidden_field_tag 'back_url', url_for(params.respond_to?(:to_unsafe_hash) ? params.to_unsafe_hash : params) %>
<%= hidden_field_tag 'project_id', @project.id if @project %>
<div class="autoscroll">
    <table class="contacts index">
    <tbody>
    <% previous_group = false %>
    <% @contacts.each do |contact| %>
        <% if @query.grouped? && (group = @query.group_by_column.value(contact)) != previous_group %>
          <% reset_cycle %>
          <tr class="group open">
            <td colspan="<%= @query.columns.size + 2 %>">
              <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
              <%= group.blank? ? 'None' : column_content(@query.group_by_column, contact) %> <span class="count">(<%= @contact_count_by_group[group] %>)</span>
              <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}", "toggleAllRowGroups(this)", :class => 'toggle-all') %>
            </td>
          </tr>
          <% previous_group = group %>
        <% end %>

        <tr class="hascontextmenu  <%= cycle('odd', 'even') %> ">
            <td class="checkbox">
                <%= check_box_tag "ids[]", contact.id, false, :onclick => "toggleContact(event, this);" %>
            </td>
            <td class="avatar">
                    <%= link_to avatar_to(contact, :size => "32"), contact_path(contact, :project_id => @project), :id => "avatar" %>
            </td>
            <td class="name">
                <h1><%= link_to contact.name, contact_path(contact, :project_id => @project) %></h1>
                <p>
                    <%= link_to contact.website, contact.website_address, :class => 'external', :only_path => true unless !contact.is_company %>
                    <%= mail_to contact.emails.first unless contact.is_company%>
                    <div><%= contact.phones.first %></div>
                </p>
            </td>
            <td class="info">
                <div class="title_and_company" >
                    <%= contact.job_title %>
                    <% if !contact.is_company %>
                        <%= " #{l(:label_crm_at_company)} " unless (contact.job_title.blank? or contact.company.blank?) %>
                        <%= contact.company %>
                    <% end %>
                </div>
                <div class="tags">
                    <%= tag_links(contact.tag_list) %>
                    <%# tag_links(RedmineCrm::TagList.from(contact.cached_tag_list)) %>
                </div>
            </td>
        </tr>
    <% end %>
    </tbody>
    </table>
 </div>
 <% end %>

redmine-5.0-private/plugins/redmine_contacts/app/views/contacts/_tags_cloud.html.erb
<div id="tags">
	<span id="single_tags">
		<h3><%= l(:label_crm_tags_plural) %></h3>
     <span class="tag_list"><%= safe_join(tags_cloud.map{|tag| tag_link(tag.name, :count => tag.count)}, ContactsSetting.monochrome_tags? ? ', ' : ' ').html_safe %></span>
	</span>

</div>

redmine-5.0-private/plugins/redmine_contacts/app/views/contacts/load_tab.js.erb
<%
    @tab = params[:tab_name]
    @partial = params[:partial]
%>
$('#tab-placeholder-<%= @tab %>').html("<%= j(render :partial => @partial) %>")