redmine-5.0-private/plugins/redmine_contacts/config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

#custom routes for this plugin
  resources :contacts, :path_names => {:contacts_notes => 'notes'} do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :contacts_notes
      post :bulk_edit, :bulk_update, :send_mails, :preview_email
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'contacts#show', :as => "tabs"
      get 'load_tab' => 'contacts#load_tab', :as => "load_tab"
    end
    resources :contacts_projects, :path => "projects", :only => [:new, :create, :destroy]
  end

  resources :projects do
    resources :contacts, :path_names => {:contacts_notes => 'notes'} do
      collection do
        get :contacts_notes
      end
    end
    resources :contact_imports, :only => [:new, :create, :show] do
      member do
        get :settings
        post :settings
        get :mapping
        post :mapping
        get :run
        post :run
      end
    end
    resources :deal_imports, :only => [:new, :create, :show] do
      member do
        get :settings
        post :settings
        get :mapping
        post :mapping
        get :run
        post :run
      end
    end
    resources :deal_categories

  end
  resources :deals do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email
      post :bulk_edit, :bulk_update, :send_mails, :update_form
      put :update_form
      delete :bulk_destroy
    end
    member do
      put :add_product, defaults: { format: :json }
    end
  end

  resources :projects do
    resources :deals, :only => [:new, :create, :index]
    resources :deal_categories, :only => [:new, :create, :index]
  end

  resources :deal_categories, :only => [:edit, :update, :destroy]

  resources :deal_statuses, :except => :show do
    collection do
      put :assign_to_project
    end
  end

  resources :projects do
    resources :crm_queries, :only => [:new, :create]
  end

  resources :crm_queries, :except => [:show]

  resources :notes

  match '/contacts_tags', :controller => 'contacts_tags', :action => 'destroy', :via => :delete

  resources :contacts_tags do
    collection do
      post :merge, :context_menucha
      get :context_menu, :merge
    end
  end

  match 'contacts/:contact_id/duplicates' => 'contacts_duplicates#index', :via => [:get, :post]

  match 'projects/:project_id/deal_categories/new' => 'deal_categories#new', :via => [:get, :post]


  match 'auto_completes/taggable_tags' => 'auto_completes#taggable_tags', :via => :get, :as => 'auto_complete_taggable_tags'
  match 'auto_completes/contact_tags' => 'auto_completes#contact_tags', :via => :get, :as => 'auto_complete_contact_tags'
  match 'auto_completes/contacts' => 'auto_completes#contacts', :via => :get, :as => 'auto_complete_contacts'
  match 'auto_completes/companies' => 'auto_completes#companies', :via => :get, :as => 'auto_complete_companies'
  match 'auto_completes/deals' => 'auto_completes#deals', :via => :get, :as => 'auto_complete_deals'

  match 'users/new_from_contact/:id' => 'users#new_from_contact', :via => :get
  match 'contacts_duplicates/:action' => 'contacts_duplicates', :via => [:get, :post]
  match 'contacts_duplicates/search' => 'contacts_duplicates#search', :via => :get, :as => 'contacts_duplicates_search'
  match 'contacts_issues/:action' => 'contacts_issues', :via => [:get, :post, :delete, :put]
  match 'contacts_vcf/:action' => 'contacts_vcf', :via => [:get, :post]
  match 'deal_contacts/:action' => 'deal_contacts', :via => [:get, :post, :delete]
  match 'deals_tasks/:action' => 'deals_tasks', :via => [:get, :post, :put]
  match 'contacts_settings/:action' => 'contacts_settings', :via => [:get, :post]
  match 'contacts_mail_handler/:action' => 'contacts_mail_handler', :via => [:get, :post]
  match 'attachments/contacts_thumbnail/:id(/:size)', :controller => 'attachments', :action => 'contacts_thumbnail', :id => /\d+/, :via => :get

redmine-5.0-private/plugins/redmine_contacts/app/helpers/contacts_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

module ContactsHelper

  def contact_tabs(contact)
    contact_tabs = []
    contact_tabs << {:name => 'notes', :partial => 'contacts/notes', :label => l(:label_crm_note_plural)} if contact.visible?
    contact_tabs << {:name => 'contacts', :partial => 'company_contacts', :label => l(:label_contact_plural) + (contact.company_contacts.visible.count > 0 ? " (#{contact.company_contacts.count})" : "")} if contact.is_company?
    contact_tabs << {:name => 'deals', :partial => 'deals/related_deals', :label => l(:label_deal_plural) + (contact.all_visible_deals.size > 0 ? " (#{contact.all_visible_deals.size})" : "") } if User.current.allowed_to?(:add_deals, @project)
    contact_tabs
  end

  def settings_contacts_tabs
    ret = [
      {:name => 'general', :partial => 'settings/contacts/contacts_general', :label => :label_general},
      {:name => 'tags', :partial => 'settings/contacts/contacts_tags', :label => :label_crm_tags_plural},
      {:name => 'deal_statuses', :partial => 'settings/contacts/contacts_deal_statuses', :label => :label_crm_deal_status_plural},
    ]
    ret.push({:name => 'hidden', :partial => 'settings/contacts/contacts_hidden', :label => :label_crm_contacts_hidden}) if params[:hidden]
    ret
  end

  def collection_for_visibility_select
    [[l(:label_crm_contacts_visibility_project), Contact::VISIBILITY_PROJECT],
     [l(:label_crm_contacts_visibility_public), Contact::VISIBILITY_PUBLIC],
     [l(:label_crm_contacts_visibility_private), Contact::VISIBILITY_PRIVATE]]
  end

  def contact_list_styles_for_select
    list_styles = [[l(:label_crm_list_excerpt), "list_excerpt"]]
    list_styles += [[l(:label_crm_list_list), "list"],
                    [l(:label_crm_list_cards), "list_cards"]]
  end

  def contacts_list_style
    list_styles = contact_list_styles_for_select.map(&:last)
    if params[:contacts_list_style].blank?
      list_style = list_styles.include?(session[:contacts_list_style]) ? session[:contacts_list_style] : RedmineContacts.default_list_style
    else
      list_style = list_styles.include?(params[:contacts_list_style]) ? params[:contacts_list_style] : RedmineContacts.default_list_style
    end
    session[:contacts_list_style] = list_style
  end

  def authorized_for_permission?(permission, project, global = false)
    User.current.allowed_to?(permission, project, :global => global)
  end

  def render_contact_projects_hierarchy(projects)
    s = ''
    project_tree(projects) do |project, level|
      s << "<ul>"
      name_prefix = (level > 0 ? ('&nbsp;' * 2 * level + '&#187; ') : '')
      s << "<li id='project_#{project.id}'>" + name_prefix + link_to_project(project)

      s += ' ' + link_to(image_tag('delete.png'),
                                 contact_contacts_project_path(@contact, :id => project.id, :project_id => @project.id),
                                 :remote => true,
                                 :method => :delete,
                                 :style => "vertical-align: middle",
                                 :class => "delete",
                                 :title => l(:button_delete)) if (projects.size > 1 && User.current.allowed_to?(:edit_contacts, project))
      s << "</li>"

      s << "</ul>"
    end
    s.html_safe
  end

  def contact_to_vcard(contact)
    return false unless ContactsSetting.vcard?

    card = Vcard::Vcard::Maker.make2 do |maker|

      maker.add_name do |name|
        name.prefix = ''
        name.given = contact.first_name.to_s
        name.family = contact.last_name.to_s
        name.additional = contact.middle_name.to_s
      end

      maker.add_addr do |addr|
        addr.preferred = true
        addr.street = contact.street1.to_s.gsub("\r\n"," ").gsub("\n"," ")
        addr.locality = contact.city.to_s
        addr.region = contact.region.to_s
        addr.postalcode = contact.postcode.to_s
        addr.country = contact.country.to_s
        addr.location = 'business'
      end

      maker.title = contact.job_title.to_s
      maker.org = contact.company.to_s
      maker.birthday = contact.birthday.to_date unless contact.birthday.blank?
      maker.add_note(contact.background.to_s.gsub("\r\n"," ").gsub("\n", ' '))

      maker.add_url(contact.website.to_s)

      contact.phones.each { |phone| maker.add_tel(phone) }
      contact.emails.each { |email| maker.add_email(email) }
    end
    avatar = contact.attachments.find_by_description('avatar')
    card = card.encode.sub("END:VCARD", "PHOTO;BASE64:" + "\n " + [File.open(avatar.diskfile).read].pack('m').to_s.gsub(/[ \n]/, '').scan(/.{1,76}/).join("\n ") + "\nEND:VCARD") if avatar && avatar.readable?

    card.to_s

  end
  def contacts_to_vcard(contacts)
    return "" unless User.current.allowed_to?(:export_contacts, @project, :global => true)
    contacts.map{|c| contact_to_vcard(c) }.join("\r\n")
  end

  def contacts_to_xls(contacts)
    return "" unless User.current.allowed_to?(:export_contacts, @project, :global => true)
    require 'spreadsheet'

    Spreadsheet.client_encoding = 'UTF-8'
    book = Spreadsheet::Workbook.new
    sheet = book.create_worksheet
    headers = [ "#",
            l(:field_is_company),
            l(:field_contact_first_name),
            l(:field_contact_middle_name),
            l(:field_contact_last_name),
            l(:field_contact_job_title),
            l(:field_contact_company),
            l(:field_contact_phone),
            l(:field_contact_email),
            l(:label_crm_address),
            l(:label_crm_city),
            l(:label_crm_postcode),
            l(:label_crm_region),
            l(:label_crm_country),
            l(:field_contact_skype),
            l(:field_contact_website),
            l(:field_birthday),
            l(:field_contact_tag_names),
            l(:label_crm_assigned_to),
            l(:field_contact_background),
            l(:field_created_on),
            l(:field_updated_on)
            ]
    order_condition = 'LOWER(name)'
    order_condition += ' COLLATE "C"' if ActiveRecord::VERSION::MAJOR < 6 && ActiveRecord::Base.connection.adapter_name.downcase =~ /postgresql/
    custom_fields = ContactCustomField.order(order_condition)
    custom_fields.each { |f| headers << f.name }
    idx = 0
    row = sheet.row(idx)
    row.replace headers

    contacts.each do |contact|
      idx += 1
      row = sheet.row(idx)
      fields = [contact.id,
                  contact.is_company ? 1 : 0,
                  contact.first_name,
                  contact.middle_name,
                  contact.last_name,
                  contact.job_title,
                  contact.company,
                  contact.phone,
                  contact.email,
                  contact.address.to_s.gsub("\r\n"," ").gsub("\n", ' '),
                  contact.city,
                  contact.postcode,
                  contact.region,
                  contact.country,
                  contact.skype_name,
                  contact.website,
                  format_date(contact.birthday),
                  contact.tag_list.to_s,
                  contact.assigned_to ? contact.assigned_to.name : "",
                  contact.background.to_s.gsub("\r\n"," ").gsub("\n", ' '),
                  format_date(contact.created_on),
                  format_date(contact.updated_on)
                  ]
      contact.custom_field_values.sort_by{|v| v.custom_field.name.downcase}.each {|custom_value| fields << RedmineContacts::Utils::CsvUtils.csv_custom_value(custom_value) }
      row.replace fields
    end

    xls_stream = StringIO.new('')
    book.write(xls_stream)

    return xls_stream.string
  end

  def mail_macro(contact, message)
    message = message.gsub(/%%NAME%%/, contact.first_name)
    message = message.gsub(/%%FULL_NAME%%/, contact.name)
    message = message.gsub(/%%COMPANY%%/, contact.company) if contact.company
    message = message.gsub(/%%LAST_NAME%%/, contact.last_name) if contact.last_name
    message = message.gsub(/%%MIDDLE_NAME%%/, contact.middle_name) if contact.middle_name
    message = message.gsub(/%%DATE%%/, format_date(Date.today.to_s))

    contact.custom_field_values.each do |value|
      message = message.gsub(/%%#{value.custom_field.name}%%/, value.value.to_s)
    end
    message
  end

  def set_flash_from_bulk_contact_save(contacts, unsaved_contact_ids)
    if unsaved_contact_ids.empty?
      flash[:notice] = l(:notice_successful_update) unless contacts.empty?
    else
      flash[:error] = l(:notice_failed_to_save_contacts,
                        :count => unsaved_contact_ids.size,
                        :total => contacts.size,
                        :ids => '#' + unsaved_contact_ids.join(', #'))
    end
  end

  def render_contact_tabs(tabs)
    if tabs.any?
      render :partial => 'common/contact_tabs', :locals => {:tabs => tabs}
    else
      content_tag 'p', l(:label_no_data), :class => "nodata"
    end
  end

  def importer_link
    project_contact_imports_path
  end

  def importer_show_link(importer, project)
    project_contact_import_path(:id => importer, :project_id => project)
  end

  def importer_settings_link(importer, project)

redmine-5.0-private/plugins/redmine_contacts/app/views/settings/contacts/_contacts.html.erb
<% extend ContactsHelper %>

<%= render_tabs settings_contacts_tabs %>

<% html_title(l(:label_settings), l(:label_contact_plural)) -%>

redmine-5.0-private/plugins/redmine_contacts/app/views/settings/contacts/_contacts_deal_statuses.html.erb
<div class="contextual">
<%= link_to l(:label_crm_deal_status_new), {:controller => "deal_statuses", :action => 'new'}, :class => 'icon icon-add' %>
</div>

<h3><%=l(:label_crm_deal_status_plural)%></h3>

<table class="list">
  <thead><tr>
  <th><%=l(:field_status)%></th>
  <th><%=l(:field_is_default)%></th>
  <th><%=l(:label_crm_deal_status_type)%></th>
  <th><%=l(:button_sort)%></th>
  <th></th>
  </tr></thead>
  <tbody>
<% for status in DealStatus.where({}).order(:status_type, :position)  %>
  <tr class="<%= cycle("odd", "even") %>">
  <td class="name"><span class="color" style="border: 1px solid #D7D7D7;background-color: <%= status.color_name %>;">&nbsp;&nbsp;&nbsp;&nbsp;</span> <%= link_to status.name, :controller => "deal_statuses", :action => 'edit', :id => status %></td>
  <td align="center" style="width:15%;"><%= checked_image status.is_default? %></td>
  <td align="center" style="width:15%;"><%= status.status_type_name %></td>
  <td align="center" style="width:15%;"><%= stocked_reorder_link(status, 'deal_status', {:controller => "deal_statuses", :action => 'update', :id => status}, :put) %></td>
  <td class="buttons">
    <%= delete_link deal_status_path(status) %>
  </td>
  </tr>
<% end %>
  </tbody>
</table>

<%= javascript_tag do %>
  $(function() { $("table.list tbody").positionedItems(); });
<% end %>

redmine-5.0-private/plugins/redmine_contacts/app/views/settings/contacts/_contacts_general.html.erb
<p>
  <label><%= l(:label_crm_user_format) %></label>
  <%= select_tag 'settings[name_format]', options_for_select(Contact::CONTACT_FORMATS.collect{|key, value| [key, value[:setting_order]]}.sort{|a, b| a[1] <=> b[1]}.collect{|f| [Contact.new(:first_name => 'Firstname', :last_name => 'Lastname', :middle_name => 'Middlename').name(f[0]), f[0].to_s]}, @settings["name_format"] ) %>
</p>
<p>
  <label><%= l(:label_crm_default_list_style) %></label>
  <%= select_tag 'settings[default_list_style]', options_for_select([[l(:label_crm_list_excerpt), "list_excerpt"], [l(:label_crm_list_list), "list"], [l(:label_crm_list_cards), "list_cards"]] , @settings["default_list_style"]) %>
</p>

<p>
  <%= label_tag 'settings_select_companies_to_deal', l(:label_crm_select_companies) %>
  <%= hidden_field_tag 'settings[select_companies_to_deal]', 0 %>
  <%= check_box_tag 'settings[select_companies_to_deal]', 1, @settings["select_companies_to_deal"].to_i > 0 %>
</p>

<p>
  <%= label_tag 'settings_cross_project_contacts', l(:label_crm_cross_project_contacts) %>
  <%= hidden_field_tag 'settings[cross_project_contacts]', 0 %>
  <%= check_box_tag 'settings[cross_project_contacts]', 1, @settings["cross_project_contacts"].to_i > 0 %>
</p>

<p>
  <label><%= l(:label_crm_post_address_format) %></label>
  <%= text_area_tag  'settings[post_address_format]', ContactsSetting.post_address_format, :rows => 5 %>
  <em class="info"><%= l(:label_crm_post_address_format_macros, :macros => '%street1%, %street2%, %city%, %town%, %postcode%, %zip%, %region%, %state%, %country%') %></em>
</p>

<p>
  <label><%= l(:label_crm_default_country) %></label>
  <%= select_tag  'settings[default_country]', options_for_select(countries_for_select, ContactsSetting.default_country) %>
</p>

<p>
  <label><%= l(:label_crm_show_in_top_menu) %></label>
  <span id="watchers_inputs">
    <span class="floating" style="margin-left: 0px;">
    <%= hidden_field_tag 'settings[contacts_show_in_top_menu]', 0 %>
    <%= check_box_tag 'settings[contacts_show_in_top_menu]', 1, @settings["contacts_show_in_top_menu"].to_i > 0 %>
    <%= l(:label_contact_plural) %>
    </span>
    <span class="floating" style="margin-left: 0px;">
    <%= hidden_field_tag 'settings[deals_show_in_top_menu]', 0 %>
    <%= check_box_tag 'settings[deals_show_in_top_menu]', 1, @settings["deals_show_in_top_menu"].to_i > 0 %>
    <%= l(:label_deal_plural) %>
    </span>
  </span>
</p>

<p>
  <label><%= l(:label_crm_show_in_app_menu) %></label>
  <span id="watchers_inputs">
    <span class="floating" style="margin-left: 0px;">
    <%= hidden_field_tag 'settings[contacts_show_in_app_menu]', 0 %>
    <%= check_box_tag 'settings[contacts_show_in_app_menu]', 1, @settings["contacts_show_in_app_menu"].to_i > 0 %>
    <%= l(:label_contact_plural) %>
    </span>
    <span class="floating" style="margin-left: 0px;">
    <%= hidden_field_tag 'settings[deals_show_in_app_menu]', 0 %>
    <%= check_box_tag 'settings[deals_show_in_app_menu]', 1, @settings["deals_show_in_app_menu"].to_i > 0 %>
    <%= l(:label_deal_plural) %>
    </span>
  </span>
</p>


<p>
  <%= label_tag 'settings_note_authoring_time', l(:label_crm_contact_note_authoring_time) %>
  <%= hidden_field_tag 'settings[note_authoring_time]', 0 %>
  <%= check_box_tag 'settings[note_authoring_time]', 1, @settings["note_authoring_time"].to_i > 0 %>
</p>


<p>
  <%= label_tag 'settings_show_closed_issues', l(:label_crm_contact_show_closed_issues) %>
  <%= hidden_field_tag 'settings[show_closed_issues]', 0 %>
  <%= check_box_tag 'settings[show_closed_issues]', 1, @settings["show_closed_issues"].to_i > 0 %>
</p>
<p>
  <%= label_tag 'settings_auto_contacts_thumbnails', l(:label_crm_thumbnails_enabled) %>
  <%= hidden_field_tag 'settings[auto_contacts_thumbnails]', 0 %>
  <%= check_box_tag 'settings[auto_contacts_thumbnails]', 1, @settings["auto_contacts_thumbnails"].to_i > 0 %>
</p>

<% unless Redmine::Thumbnail.convert_available?  %>
<p>
  <label><%= l(:label_crm_max_thumbnail_file_size) %></label>
  <%= text_field_tag 'settings[max_contacts_thumbnail_file_size]', @settings["max_contacts_thumbnail_file_size"], :size => 6 %> <%= l(:"number.human.storage_units.units.kb") %>
</p>
<% end %>

<p>
  <%= label_tag 'settings_monochrome_tags', l(:label_crm_monochrome_tags) %>
  <%= hidden_field_tag 'settings[monochrome_tags]', 0 %>
  <%= check_box_tag 'settings[monochrome_tags]', 1, @settings["monochrome_tags"].to_i > 0 %>
</p>

redmine-5.0-private/plugins/redmine_contacts/app/views/settings/contacts/_contacts_hidden.html.erb
<p>
  <label>Monochrome tags</label>
  <%= check_box_tag 'settings[monochrome_tags]', 1, @settings[:monochrome_tags] %>
</p>

redmine-5.0-private/plugins/redmine_contacts/app/views/settings/contacts/_contacts_tags.html.erb
<% tags = Contact.all_tag_counts(:order => :name) %>

<h3><%= l(:label_crm_tags_plural) %></h3>

<% unless tags.empty? %>
<table class  = "list issues">
  <thead>
    <tr>
      <th class="checkbox hide-when-print">
        <%= link_to image_tag('toggle_check.png'), {},
                              :onclick => 'toggleCRMIssuesSelection(this); return false;',
                              :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
      </th>
      <th><%= l(:field_name) %></th>
      <th align="center" style="width:10%;"> </th>
    </tr>
  </thead>
  <tbody>
    <% tags.each do |tag| %>
      <tr id="<%= tag.id %>" class="<%= cycle("odd", "even") %> hascontextmenu ">
        <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", tag.id, false, :id => nil) %></td>
        <td class="name"><%= tag_link(tag.name) %></td>
        <td class="buttons">
          <%= link_to l(:button_edit), edit_contacts_tag_path(tag),
                                         :class => 'icon icon-edit' %>

          <%= link_to l(:button_delete), contacts_tags_path(:ids => tag),
                                         :method => :delete,
                                         :data => {:confirm => l(:text_are_you_sure)},
                                         :class => 'icon icon-del' %>
          </td>

      </tr>

    <% end %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>