redmine-5.0-private/plugins/redmine_contacts/config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

#custom routes for this plugin
  resources :contacts, :path_names => {:contacts_notes => 'notes'} do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :contacts_notes
      post :bulk_edit, :bulk_update, :send_mails, :preview_email
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'contacts#show', :as => "tabs"
      get 'load_tab' => 'contacts#load_tab', :as => "load_tab"
    end
    resources :contacts_projects, :path => "projects", :only => [:new, :create, :destroy]
  end

  resources :projects do
    resources :contacts, :path_names => {:contacts_notes => 'notes'} do
      collection do
        get :contacts_notes
      end
    end
    resources :contact_imports, :only => [:new, :create, :show] do
      member do
        get :settings
        post :settings
        get :mapping
        post :mapping
        get :run
        post :run
      end
    end
    resources :deal_imports, :only => [:new, :create, :show] do
      member do
        get :settings
        post :settings
        get :mapping
        post :mapping
        get :run
        post :run
      end
    end
    resources :deal_categories

  end
  resources :deals do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email
      post :bulk_edit, :bulk_update, :send_mails, :update_form
      put :update_form
      delete :bulk_destroy
    end
    member do
      put :add_product, defaults: { format: :json }
    end
  end

  resources :projects do
    resources :deals, :only => [:new, :create, :index]
    resources :deal_categories, :only => [:new, :create, :index]
  end

  resources :deal_categories, :only => [:edit, :update, :destroy]

  resources :deal_statuses, :except => :show do
    collection do
      put :assign_to_project
    end
  end

  resources :projects do
    resources :crm_queries, :only => [:new, :create]
  end

  resources :crm_queries, :except => [:show]

  resources :notes

  match '/contacts_tags', :controller => 'contacts_tags', :action => 'destroy', :via => :delete

  resources :contacts_tags do
    collection do
      post :merge, :context_menucha
      get :context_menu, :merge
    end
  end

  match 'contacts/:contact_id/duplicates' => 'contacts_duplicates#index', :via => [:get, :post]

  match 'projects/:project_id/deal_categories/new' => 'deal_categories#new', :via => [:get, :post]


  match 'auto_completes/taggable_tags' => 'auto_completes#taggable_tags', :via => :get, :as => 'auto_complete_taggable_tags'
  match 'auto_completes/contact_tags' => 'auto_completes#contact_tags', :via => :get, :as => 'auto_complete_contact_tags'
  match 'auto_completes/contacts' => 'auto_completes#contacts', :via => :get, :as => 'auto_complete_contacts'
  match 'auto_completes/companies' => 'auto_completes#companies', :via => :get, :as => 'auto_complete_companies'
  match 'auto_completes/deals' => 'auto_completes#deals', :via => :get, :as => 'auto_complete_deals'

  match 'users/new_from_contact/:id' => 'users#new_from_contact', :via => :get
  match 'contacts_duplicates/:action' => 'contacts_duplicates', :via => [:get, :post]
  match 'contacts_duplicates/search' => 'contacts_duplicates#search', :via => :get, :as => 'contacts_duplicates_search'
  match 'contacts_issues/:action' => 'contacts_issues', :via => [:get, :post, :delete, :put]
  match 'contacts_vcf/:action' => 'contacts_vcf', :via => [:get, :post]
  match 'deal_contacts/:action' => 'deal_contacts', :via => [:get, :post, :delete]
  match 'deals_tasks/:action' => 'deals_tasks', :via => [:get, :post, :put]
  match 'contacts_settings/:action' => 'contacts_settings', :via => [:get, :post]
  match 'contacts_mail_handler/:action' => 'contacts_mail_handler', :via => [:get, :post]
  match 'attachments/contacts_thumbnail/:id(/:size)', :controller => 'attachments', :action => 'contacts_thumbnail', :id => /\d+/, :via => :get

redmine-5.0-private/plugins/redmine_contacts/app/helpers/deals_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

module DealsHelper
  include ContactsHelper
  def collection_for_status_select
    deal_statuses.collect{|s| [s.name, s.id.to_s]}
  end

  def deal_status_options_for_select(select="")
     options_for_select(collection_for_status_select, select)
  end

  def deal_statuses
    (!@project.blank? ? @project.deal_statuses : DealStatus.order("#{DealStatus.table_name}.status_type, #{DealStatus.table_name}.position")) || []
  end

  def deal_status_url(status_id, options={})
    {:controller => 'deals',
     :action => 'index',
     :set_filter => 1,
     :project_id => @project,
     :fields => [:status_id],
     :values => {:status_id => [status_id]},
     :operators => {:status_id => '='}}.merge(options)
  end

  def pipeline_status_tag(deal_status, count, index)
    total = @processor.scope.count
    width ||= 20 if deal_status.is_won?
    width ||= 40 if deal_status.is_lost?
    width ||= (100 - 20) * (count.to_f / total.to_f) + 20
    width_style = index == 0 ? "" : "width: #{width}%"
    status_tag = content_tag(:span, deal_status.name)
    content_tag(:span, status_tag, :class => "tag-label-color", :style => "background-color:#{deal_status.color_name};color:white; #{width_style}")
  end

  def remove_contractor_link(contact)
    link_to(image_tag('delete.png'),
      {:controller => "deal_contacts", :action => 'delete', :project_id => @project, :deal_id => @deal, :contact_id => contact},
      :remote => true,
      :method => :delete,
      :data => {:confirm => l(:text_are_you_sure)},
      :class  => "delete", :title => l(:button_delete)) if  User.current.allowed_to?(:edit_deals, @project)
  end

  def link_to_deal(deal)
    link_to deal.name, deal_path(deal)
  end

  def deal_list_styles_for_select
    [[l(:label_crm_list_excerpt), "list_excerpt"],
     [l(:label_crm_list_list), "list"],
     [l(:label_crm_list_board), "list_board"],
     [l(:label_calendar), "crm_calendars/crm_calendar"],
     [l(:label_crm_pipeline), "list_pipeline"]]
  end

  def deals_list_style
    list_styles = deal_list_styles_for_select.map(&:last)
    if params[:deals_list_style].blank?
      list_style = list_styles.include?(session[:deals_list_style]) ? session[:deals_list_style] : RedmineContacts.default_list_style.gsub("list_cards", "list_board")
    else
      list_style = list_styles.include?(params[:deals_list_style]) ? params[:deals_list_style] : RedmineContacts.default_list_style.gsub("list_cards", "list_board")
    end
    session[:deals_list_style] = list_style
  end

  def retrieve_deals_query
    if params[:status_id] || !params[:period].blank? || !params[:category_id].blank? || !params[:assigned_to_id].blank?
      session[:deals_query] = {:project_id => (@project ? @project.id : nil),
                               :status_id => params[:status_id],
                               :category_id => params[:category_id],
                               :period => params[:period],
                               :assigned_to_id => params[:assigned_to_id]}
    else
      if api_request? || params[:set_filter] || session[:deals_query].nil? || session[:deals_query][:project_id] != (@project ? @project.id : nil)
        session[:deals_query] = {}
      else
        params.merge!(session[:deals_query])
      end
    end
  end

  def pipeline_prices(scope)
    prices_collection_by_currency(scope.group_by(&:currency).map{|k,v| [k, v.inject(0) { |sum, x| sum + x.price.to_f } ] }).join(' / ').html_safe
  end

  def deals_to_csv(deals)
    return "" unless User.current.allowed_to?(:export_contacts, @project, :global => true)
    decimal_separator = l(:general_csv_decimal_separator)
    encoding = 'utf-8'
    export = FCSV.generate(:col_sep => l(:general_csv_separator)) do |csv|
      # csv header fields
      headers = [ "#",
                  l(:field_name, :locale => :en),
                  l(:field_background, :locale => :en),
                  l(:field_currency, :locale => :en),
                  l(:field_price, :locale => :en),
                  l(:label_crm_probability, :locale => :en),
                  l(:label_crm_expected_revenue, :locale => :en),
                  l(:field_due_date, :locale => :en),
                  l(:field_author, :locale => :en),
                  l(:field_assigned_to, :locale => :en),
                  l(:field_status, :locale => :en),
                  l(:field_contact, :locale => :en),
                  l(:field_category, :locale => :en),
                  l(:field_created_on, :locale => :en),
                  l(:field_updated_on, :locale => :en)
                  ]

      custom_fields = DealCustomField.order(:name)
      custom_fields.each {|f| headers << f.name}
      csv << headers.collect {|c| Redmine::CodesetUtil.from_utf8(c.to_s, encoding) }
      # csv lines
      deals.each do |deal|
        fields = [deal.id,
                  deal.name,
                  deal.background,
                  deal.currency,
                  deal.price,
                  deal.probability,
                  deal.expected_revenue,
                  format_date(deal.due_date),
                  deal.author,
                  deal.assigned_to,
                  deal.status,
                  deal.contact,
                  deal.category,
                  format_date(deal.created_on),
                  format_date(deal.updated_on)
                  ]
        deal.custom_field_values.sort_by{|v| v.custom_field.name}.each {|custom_value| fields << RedmineContacts::Utils::CsvUtils.csv_custom_value(custom_value) }
        csv << fields.collect {|c| Redmine::CodesetUtil.from_utf8(c.to_s, encoding) }
      end
    end
    export
  end

  def importer_link
    project_deal_imports_path
  end

  def importer_show_link(importer, project)
    project_deal_import_path(:id => importer, :project_id => project)
  end

  def importer_settings_link(importer, project)
    settings_project_deal_import_path(:id => importer, :project => project)
  end

  def importer_run_link(importer, project)
    run_project_deal_import_path(:id => importer, :project_id => project, :format => 'js')
  end

  def importer_link_to_object(deal)
    link_to deal.name, deal_path(deal)
  end

  def _project_deals_path(project, *args)
    if project
      project_deals_path(project, *args)
    else
      deals_path(*args)
    end
  end
end

redmine-5.0-private/plugins/redmine_contacts/app/views/deals/_attributes.html.erb
<% if @deal.custom_field_values.any? %>
<div id="attributes">

	<h3><%= l(:label_deal) %></h3>
	<table class="attributes">
		<% @deal.custom_field_values.each do |custom_value| %>
			<% if !custom_value.value.blank? %>
			<tr> <th class = "custom_field"><%= custom_value.custom_field.name %>:</th><td> <%=h show_value(custom_value) %></td> </tr>
			<% end %>
		<% end %>
	</table>

</div>
<% end %>

redmine-5.0-private/plugins/redmine_contacts/app/views/deals/_custom_field_form.html.erb
<p><%= form.check_box :is_filter %></p>
<p><%= form.check_box :visible, :label => l(:label_crm_contacts_show_in_list) %></p>
<% if (@custom_field.respond_to?(:format) && @custom_field.format.searchable_supported) || !@custom_field.respond_to?(:format) %>
<p><%= form.check_box :searchable %></p>
<% end %>

redmine-5.0-private/plugins/redmine_contacts/app/views/deals/_deals_statistics.html.erb
<% if deal_statuses.any? %>
	<div id="deals_statistics">
		<div class="contextual">
			<%= link_to l(:label_crm_sales_funnel), {:controller => 'deals', :action => 'index', :project_id => @project, :deals_list_style => 'list_pipeline'} %>
		</div>
		<h3><%= l(:label_crm_statistics) %></h3>
		<table class="deals_statistics">
			<% deal_statuses.each do |deal_status| %>
			<tr>
				<td>
					<span class="tag-label-color" style=<%= "background-color:#{deal_status.color_name};color:white;" %> >
						<%= link_to "#{deal_status.name}(#{@project ? @project.deals.visible.with_status(deal_status.id).count : Deal.visible.with_status(deal_status.id).count})".html_safe, deal_status_url(deal_status.id, :project_id => @project) %>
					</span>
				</td>
				<td>
					<strong>
						<%= prices_collection_by_currency(Deal.by_project(@project).visible.where(:status_id => deal_status.id).group(:currency).sum(:price), :hide_zeros => true).join(' / ').html_safe %>
					</strong>
				</td>
			</tr>
			<% end %>
		</table>
	</div>
<% end %>

redmine-5.0-private/plugins/redmine_contacts/app/views/deals/_form.html.erb
<%= labelled_fields_for :deal, @deal do |f| %>
<%= call_hook(:view_deals_form_details_top, {:deal => @deal, :form => f }) %>

  <p><%= f.text_field :name, :label=>l(:field_deal_name), :size => 80, :required => true %></p>
  <p><%= f.select :project_id, project_tree_options_for_select(Deal.allowed_target_projects, :selected => @deal.project), {:required => true}, :onchange => "updateCustomForm('#{escape_javascript update_form_deals_path(:id => @deal, :format => 'js')}', '#deal_form')" %></p>
  <p class  = "notes"><%= f.text_area :background , :cols => 80, :rows => 8, :class => 'wiki-edit', :label=>l(:field_deal_background)  %></p>  <%= wikitoolbar_for 'deal_background' %>

<div id="attributes" class="attributes">
  <div class="splitcontent">
    <div class="splitcontentleft">
      <% if @project.deal_statuses.any? %>
        <p><%= f.select :status_id, collection_for_status_select, :include_blank => false, :label=>l(:field_contact_status) %></p>
        <% end %>

      <p>
        <%= label_tag :deal_contact_id,  RedmineContacts.companies_select ? l(:label_crm_company) : l(:label_contact) %>
        <%= select_contact_tag('deal[contact_id]',
            @deal.contact,
            :include_blank => true,
            :add_contact => true,
            :is_company => RedmineContacts.companies_select) %>
      </p>
      <p>
      <% if RedmineContacts.products_plugin_installed? %>
        <%= f.text_field :price, :label => l(:field_deal_price), :size => 10, :disabled => @deal.lines.present? %>
      <% else %>
        <%= f.text_field :price, :label => l(:field_deal_price), :size => 10 %>
      <% end %>
        <%= select_tag "deal[currency]", options_for_select(collection_for_currencies_select(ContactsSetting.default_currency, ContactsSetting.major_currencies), @deal.currency), :include_blank => true, :style => "width: initial;"
          %>
      </p>
      <p><%= f.select :assigned_to_id, (@project.assignable_users.collect {|m| [m.name, m.id]}), :include_blank => true, :label => l(:label_crm_assigned_to) %></p>
    </div>

    <div class="splitcontentright">
      <% unless @project.deal_categories.empty? %>
        <p><%= f.select :category_id, (@project.deal_categories.collect {|c| [c.name, c.id]}), :include_blank => true %></p>
      <% end %>
      <p><%= f.select :probability, ((0..10).to_a.collect {|r| ["#{r*10} %", r*10] }), :label => l(:label_crm_probability), :include_blank => true %></p>
      <p><%= f.text_field :due_date, :label => l(:field_due_date), :size => 12, :type => 'date', :value => f.object.due_date.try(:to_date) %><%= calendar_for('deal_due_date') %></p>
    </div>
  </div>
</div>

<div style="clear:both;"> </div>

<% custom_field_values = @deal.custom_field_values %>
<div class="splitcontent">
  <div class="splitcontentleft">
  <% i = 0 %>
  <% split_on = (custom_field_values.size / 2.0).ceil - 1 %>
  <% custom_field_values.each do |value| %>
    <p><%= custom_field_tag_with_label :deal, value, :required => value.custom_field.is_required? %></p>
  <% if i == split_on -%>
  </div><div class="splitcontentright">
  <% end -%>
  <% i += 1 -%>
  <% end -%>
  </div>
</div>
<% if RedmineContacts.products_plugin_installed? %>
  <p class="<%= 'hol' if @deal.lines.present? %>">
    <%= label_tag l(:label_deal_items) %>
    <span><%= link_to('Add new', 'javascript:void(0)', :onclick => 'toogleDealItems(this); return false;', :class => 'icon icon-add') %></span>
  <p>
  <%= field_set_tag(l(:label_deal_items), :class => "deal_items #{'hol' unless @deal.lines.present?}") do %>
    <%= render :partial =>'shared/new_product_line', :locals => { :form => f, :parent_object => @deal} %>
  <% end %>
<% end %>
<%= call_hook(:view_deals_form_details_bottom, {:deal => @deal, :form => f }) %>
<% end %>

redmine-5.0-private/plugins/redmine_contacts/app/views/deals/_list_board.html.erb
<% if deal_statuses.any? %>
  <% if User.current.allowed_to?(:edit_deals, @project) %>
    <script>
      $(function() {

        $(".deal-status-col").droppable({
            activeClass: 'droppable-active',
            hoverClass: 'droppable-hover',
            accept: '.deal-card',
            tolerance: 'pointer',
            drop: function (event, ui) {
                ui.draggable.prependTo(this);
                $.ajax({
                  url: '<%= escape_javascript deals_path %>/' + ui.draggable.data('id'),
                  type: 'PUT',
                  dataType : "script",
                  data: {
                    deal: {status_id: $(this).data("id")},
                    status_id: $("#operators_status_id").val()
                  },
                  success: function(data){

                  }
                });
            }
        });

        $(".deal-card").draggable({
          containmentType: "parent",
          helper: "clone",
          start: function (event, ui) {
            $(ui.helper).addClass("draggable-active")
          }
        });

        // $(".deal-status-col" ).sortable({
        //   connectWith: ".deal-status-col",
        //   placeholder: "sortable-placeholder",
        //   receive: function (event, ui) {
        //       var deal_id = ui.item.data('id');
        //       var status_id = $(this).data("id");
        //       $.ajax({
        //          url: '<%= escape_javascript deals_path %>/' + deal_id + '.json',
        //          dataType : "json",
        //          type: 'PUT',
        //          data: {deal: {status_id: status_id}}
        //       });
        //   }
        // }).disableSelection();

      });
    </script>
  <% end %>

  <%= form_tag({}, :data => {:cm_url => context_menu_deals_path}) do -%>
    <%= hidden_field_tag 'back_url', url_for(params.respond_to?(:to_unsafe_hash) ? params.to_unsafe_hash : params) %>
    <%= hidden_field_tag 'project_id', @project.id if @project %>
    <% board_statuses = params[:status_id] == 'o' ? deal_statuses.open : deal_statuses %>
  <div class="autoscroll">
      <table class="list deal-board ">
        <thead class="deals_counts">
          <%= render :partial => 'board_deals_counts' %>
        </thead>
        <tr style="text-align: center;white-space: nowrap;" class="deal <%= cycle('odd', 'even') %>">

        <% board_statuses.each do |deal_status| %>
          <td class="deal-status-col <%='open' if deal_status.is_open? %> <%='won' if deal_status.is_won? %> <%='lost' if deal_status.is_lost? %> <%='closed' if deal_status.is_closed? %>" data-id="<%= deal_status.id %>">
          <% @deals.where(:status_id => deal_status.id).order("#{Deal.table_name}.updated_on DESC").each do |deal| %>
          <div class="deal-card" data-id="<%= deal.id %>">
              <p class="amount">
                <strong><%= deal.price_to_s %></strong>
                  <%= content_tag(:span, " (#{deal.probability}%)" ) if deal.probability  %>
              </p>
              <p class="name" ><%= link_to deal.name, deal_path(deal) %></p>
              <% if deal.contact %>
              <p class="info">
                <span class="contact"><%= contact_tag(deal.contact) %></span>
              </p>
              <% end %>
          </div>
          <% end %>
          </td>

          <% end %>
        </tr>

        <thead class="total">
          <%= render :partial => 'board_total' %>
        <!-- <tr>
          <% board_statuses.each do |deal_status| %>
          <th style="width: <%= 100/board_statuses.size %>%;" data-id="<%= deal_status.id %>">
            <%=  prices_collection_by_currency(@deals_scope.group(:currency).where(:status_id => deal_status.id).sum(:price), :hide_zeros => true).join('<br/>').html_safe %>
          </th>
          <% end %>
        </tr> -->
        </thead>

      </table>
  </div>

  <% end %>
<% else %>
  <p class="nodata"><%= l(:text_crm_no_deal_statuses_in_project) %></p>
<% end %>

redmine-5.0-private/plugins/redmine_contacts/app/views/deals/edit.html.erb
<h2><%= l(:label_crm_deal_edit_information) %></h2>

<%= labelled_form_for :deal, @deal, :url => {:action => 'update', :id => @deal}, :html => {:method => :put, :id => "deal_form"} do |f|  %>
  <%= error_messages_for 'deal' %>
  <div class="box tabular">
    <div id="all_attributes">
    <%= render :partial => 'form', :locals => {:f => f}  %>
    </div>
  </div>
  <%= submit_tag l(:button_save) -%>
<% end -%>

<% content_for :header_tags do %>
  <%= javascript_include_tag :contacts, :plugin => 'redmine_contacts'  %>
  <%= robot_exclusion_tag %>
<% end %>

redmine-5.0-private/plugins/redmine_contacts/app/views/deals/show.html.erb
<div class="contextual">
  <%= watcher_link(@deal, User.current) %>
  <%= link_to l(:button_edit), edit_deal_path(@deal), :class => 'icon icon-edit' if User.current.allowed_to?(:edit_deals, @project) %>
    <%= link_to l(:button_duplicate), new_project_deal_path(@project, :copy_from => @deal), :class => 'icon icon-duplicate' if User.current.allowed_to?(:add_deals, @project) %>
  <%= link_to l(:button_delete), deal_path(@deal), :data => {:confirm => l(:text_are_you_sure)}, :method => :delete, :class => 'icon icon-del' if User.current.allowed_to?(:delete_deals, @project) %>
</div>
<h2><%= "#{l(:label_deal)} ##{@deal.id}" %></h2>
<div class="deal details">

  <table class="subject_header">
    <tr>
      <td class="avatar"><%= avatar_to(@deal, :size => "64") %></td>
      <td class="name" style="vertical-align: top;">
        <h1><%= @deal.contact.name + ": " if @deal.contact %> <%= @deal.name %></h1>
        <p class="author">
        <%= authoring @deal.created_on, @deal.author %>.
        <% if @deal.created_on != @deal.updated_on %>
        <%= l(:label_updated_time, time_tag(@deal.updated_on)).html_safe %>.
        <% end %>
        </p>
        <p><%= @deal.category %></p>
        <% if @deal.status && @project.deal_statuses.any? %>
          <div id="deal-status">
            <%= deal_status_tag(@deal.status) %>
            <% if authorize_for('deals', 'edit') %>
            <span class="contextual">
              <%= link_to l(:label_crm_deal_change_status), {}, :onclick => "$('#edit_status_form').show(); $('#deal-status').hide(); return false;", :id => 'edit_status_link' %>
            </span>
            <% end %>
          </div>
          <%= form_tag( {:controller => 'deals',
                     :action => 'update',
                     :project_id => @project,
                     :id => @deal },
                 :method => :put,
                   :multipart => true,
                 :id => "edit_status_form",
                 :style => "display:none; size: 100%" ) do %>
            <%= select :deal, :status_id, options_for_select(collection_for_status_select, @deal.status_id.to_s), { :include_blank => false } %>
            <%= submit_tag l(:button_save), :class => "button-small" %>
            <%= link_to l(:button_cancel), {}, :onclick => "$('#edit_status_form').hide(); $('#deal-status').show(); return false;"  %>
            <br>

          <% end %>
        <% end %>
      </td>
      <% if !@deal.price.blank? || !@deal.due_date.blank? || !@deal.probability.blank? %>
      <td class="subject_info">
        <ul>
          <% if !@deal.price.blank?  %>
          <li class="price icon <%= deal_currency_icon(@deal.currency) %>" title="Price"><%= @deal.price_to_s %></li>
          <% end %>

          <% if !@deal.due_date.blank?  %>
          <li class="price icon icon-date" title="Due date"><%= format_date(@deal.due_date) %></li>
          <% end %>

          <% if !@deal.probability.blank?  %>
          <li class="price icon icon-rosette" title="Probability"><%= @deal.probability %>%</li>
          <% end %>

        </ul>
      </td>
      <% end %>

    </tr>
  </table>
  <% if RedmineContacts.products_plugin_installed? %>
    <% if @deal.lines.present? %>
      <% @lines_name = :label_deal_items %>
      <%= render :partial => 'shared/product_lines', :locals => { :parent_object => @deal, :total_price => @deal.price_to_s } %>
    <% end %>
  <% end %>

  <%= call_hook(:view_deals_show_details_bottom, {:deal => @deal }) %>

   <% if authorize_for('notes', 'create') %>
  <hr />
  <%= render :partial => 'notes/add', :locals => {:note_source => @deal} %>
  <% end %>
</div>

<div id="comments">
  <h3><%= l(:label_crm_note_plural) %></h3>
  <div id="notes">
    <% @deal_events.each do |deal_event| %>
      <% if deal_event[:object].is_a?(DealNote) %>
        <%= render :partial => 'notes/note_item', :object => deal_event[:object], :locals => {:note_source => @deal} %>
      <% end %>
      <% if deal_event[:object].is_a?(DealProcess) %>
        <%= render :partial => 'process_item', :object => deal_event[:object], :locals => {:note_source => @deal} %>
      <% end %>
    <% end %>
  </div>

</div>

<% content_for :sidebar do %>
  <%= call_hook(:view_deals_sidebar_top, :deal => @deal) %>
  <%= render partial: 'attributes' %>
  <%= render partial: 'common/responsible_user', object: @deal %>
  <%= render partial: 'deal_contacts/contacts' %>
  <%= render partial: 'common/related_issues', locals: { issues: @deal_issues }  %>
  <%= render partial: 'common/notes_attachments', object: @deal_attachments, locals: { container: @deal } %>

    <% if !@deal.background.blank? %>
      <h3><%= l(:label_crm_background_info) %></h3>
    <div class="wiki"><%= textilizable(@deal, :background) %></div>
    <% end %>

  <% if User.current.allowed_to?(:add_issue_watchers, @project) ||
    (@deal.watchers.present? && User.current.allowed_to?(:view_issue_watchers, @project)) %>
    <div id="watchers">
      <%= render :partial => 'watchers/watchers', :locals => {:watched => @deal} %>
    </div>
  <% end %>

  <%= call_hook(:view_deals_sidebar_bottom, :deal => @deal) %>
<% end %>

<% html_title "#{l(:label_deal)} ##{@deal.id}: #{@deal.name}" %>

<% content_for :header_tags do %>
  <%= javascript_include_tag :contacts, :plugin => 'redmine_contacts' %>
  <meta name = "format-detection" content = "telephone=no">
<% end %>